### PR TITLE
Add plugins

### PR DESCRIPTION
**Pull request by hazim1093**

### CODE REVIEW

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/jenkins:2.9.5-SNAPSHOT-PR-5-1`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/jenkins:2.9.5-SNAPSHOT-PR-5-2`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/jenkins:2.9.5-SNAPSHOT-PR-5-3`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/jenkins:2.9.5-SNAPSHOT-PR-5-4`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/jenkins:2.9.5-SNAPSHOT-PR-5-5`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/jenkins:2.9.5-SNAPSHOT-PR-5-6`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/jenkins:2.9.5-SNAPSHOT-PR-5-7`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/jenkins:2.9.5-SNAPSHOT-PR-5-8`

**Review by rasheedamir — APPROVED** [review]
Looks good

**Pull request merged**
