### PR TITLE
Add Plugins

### PR DESCRIPTION
**Pull request by hazim1093**

### CODE REVIEW

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/jenkins:2.9.5-SNAPSHOT-PR-2-1`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/jenkins:2.9.5-SNAPSHOT-PR-2-2`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/jenkins:2.9.5-SNAPSHOT-PR-2-3`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/jenkins:2.9.5-SNAPSHOT-PR-2-4`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/jenkins:2.9.5-SNAPSHOT-PR-2-5`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/jenkins:2.9.5-SNAPSHOT-PR-2-6`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/jenkins:2.9.5-SNAPSHOT-PR-2-7`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/jenkins:2.9.5-SNAPSHOT-PR-2-8`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/jenkins:2.9.5-SNAPSHOT-PR-2-9`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/jenkins:2.9.5-SNAPSHOT-PR-2-10`

**Review by rasheedamir — APPROVED** [review]
Looks good

**Pull request merged**
